# Generated by Django 3.0.8 on 2020-07-05 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='WriterBlog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('postTitle', models.CharField(max_length=30, verbose_name='포스트제목')),
                ('postExp', models.TextField(verbose_name='포스트내용')),
                ('postDate', models.DateField(auto_now_add=True, verbose_name='포스트등록날짜')),
            ],
        ),
    ]
